@startuml

actor Librarian as librarian

boundary LibrarianUI as UI
control LibraryHttpHandler as httpHandler



librarian -> UI: add title
librarian -> UI: add author
librarian -> UI: add isbn
librarian -> UI: Request to add book

UI -> httpHandler: send request with json data
activate httpHandler

create Book
httpHandler -> Book : new Book(title, author, isbn)
activate Book
return newbook
deactivate Book

participant "library:Library" as biblio

httpHandler -> biblio: addBook(newbook)
activate biblio
return success
deactivate biblio

httpHandler -> UI: return success


@enduml
